import { Debt } from '@/lib/types/debt';

// Mock data for demo/screenshots
export const MOCK_DEBTS: Debt[] = [
  {
    id: '1',
    name: 'Chase Credit Card',
    category: 'credit_card',
    original_balance: 8500,
    current_balance: 4250,
    interest_rate: 0.2499,
    minimum_payment: 175,
    due_date: 15,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Car Loan',
    category: 'auto_loan',
    original_balance: 25000,
    current_balance: 18750,
    interest_rate: 0.0699,
    minimum_payment: 450,
    due_date: 1,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Student Loan',
    category: 'student_loan',
    original_balance: 35000,
    current_balance: 28000,
    interest_rate: 0.0525,
    minimum_payment: 350,
    due_date: 20,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Best Buy Card',
    category: 'credit_card',
    original_balance: 2000,
    current_balance: 0,
    interest_rate: 0.2199,
    minimum_payment: 50,
    due_date: 10,
    status: 'paid_off',
    paid_off_date: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_DATA = {
  debts: MOCK_DEBTS,
  activeDebts: MOCK_DEBTS.filter((d) => d.status === 'active'),
  paidOffDebts: MOCK_DEBTS.filter((d) => d.status === 'paid_off'),
  totalOriginal: 70500,
  totalBalance: 51000,
  totalPaid: 19500,
  monthlyPayment: 975,
  interestSaved: 2847.5,
  debtFreeDate: 'Mar 2028',
  priorityDebt: MOCK_DEBTS[0],
};
